import os
from datetime import datetime
import structlog
from supabase import create_client, Client
from app.config import get_settings

logger = structlog.get_logger()
settings = get_settings()

class ReportAgent:
    def __init__(self):
        self.reports_dir = settings.REPORTS_DIR
        if not os.path.exists(self.reports_dir):
            os.makedirs(self.reports_dir)
            
        # Initialize Supabase Client if keys exist
        self.supabase: Client = None
        if settings.SUPABASE_URL and settings.SUPABASE_KEY:
            try:
                self.supabase = create_client(settings.SUPABASE_URL, settings.SUPABASE_KEY)
            except Exception as e:
                logger.warning("supabase_init_failed", error=str(e))

    async def run(self, narratives: list, conflicts: list, ideas: str, stats: dict):
        logger.info("agent_start", agent="ReportAgent")
        
        date_str = datetime.now().strftime("%Y-%m-%d")
        week_num = datetime.now().isocalendar()[1]
        
        # Format Sections (Reuse logic or refactor - kept same for brevity)
        conflict_section = "\n".join([str(c) for c in conflicts]) if conflicts else "No significant cross-source conflicts detected this week."
        narrative_section = ""
        for n in narratives:
            narrative_section += f"### {n.domain}\n*   **Narrative:** {n.narrative_text}\n*   **Sentiment:** {n.sentiment}\n\n"

        report_content = f"""# 🇮🇳 India Discourse Intelligence Report: Week {week_num}, {datetime.now().year}

**Date:** {date_str}
**Stats:** {stats}

---

## 1. Executive Summary
This week saw activity across {len(narratives)} domains.

---

## 2. Domain-Wise Narratives
{narrative_section}

---

## 3. Cross-Source Validation
> [!WARNING]
> **Conflict Analysis**
> {conflict_section}

---

## 4. Top 10 Actionable Ideas
{ideas}

---
*System generated by India Discourse Intelligence (Cloud Optimized).*
"""
        
        # 1. Save Local
        filename = f"report_week_{week_num}.md"
        filepath = os.path.join(self.reports_dir, filename)
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(report_content)
        
        # 2. Upload to Supabase Phase
        public_url = None
        if self.supabase:
            try:
                with open(filepath, 'rb') as f:
                    self.supabase.storage.from_(settings.SUPABASE_BUCKET).upload(
                        path=f"reports/{datetime.now().year}/{filename}",
                        file=f,
                        file_options={"content-type": "text/markdown; charset=utf-8", "upsert": "true"}
                    )
                # Get Public URL (if bucket is public)
                public_url = self.supabase.storage.from_(settings.SUPABASE_BUCKET).get_public_url(f"reports/{datetime.now().year}/{filename}")
                logger.info("report_uploaded", url=public_url)
            except Exception as e:
                logger.error("supabase_upload_failed", error=str(e))

        return {"status": "success", "path": filepath, "cloud_url": public_url}
